config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :questions do
    resources :answers, only: [ :create]
  end

  resources :answers, only:[ :update ]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :body, presence: true, length: { minimum: 5 }
  validates :question_id, presence: true
  validates :user_id, presence: true
end

app/models/original_user.rb
class OriginalUser < ActiveRecord::Base
  has_many :questions
  has_many :answers

  validates :username, presence: true
end

class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, presence: true, length: { minimum: 40 }
  validates :body, presence: true, length: { minimum: 150 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  def self.from_omniauth(auth)
    where(auth.slice(provider: auth.provider, uid: auth.uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def update
    current_user
    @best_answer = Answer.find(params[:id])
    @question = @best_answer.question
    @answer = Answer.new
    @answers = @question.answers.order(best: :desc, created_at: :asc)

    if @current_user.nil?
      flash[:notice] = "You must log in"
      redirect_to question_path(@question)
    elsif @current_user.id != @question.user_id
      flash[:notice] = "You do not have permission to edit this question"
      redirect_to question_path(@question)
    else
      @answers.update_all best: false
      @best_answer.best = true
      @best_answer.save
      render 'questions/show'
    end
  end

  def create
    current_user
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answers = @question.answers.order(created_at: :asc)

    if @current_user.nil?
      flash[:notice] = 'Please sign in before deleting a question'
      render 'questions/show'
    else
      @answer.question = @question
      @answer.user_id = @current_user.id
      if @answer.save
        redirect_to question_path(@question)
      else
        flash[:notice] = @answer.errors.full_messages.join(", ")
        render 'questions/show'
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :user_id, :best)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      :user_id
    )
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :DESC)
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(best: :desc, created_at: :asc)
  end

  def new
    current_user
    @question = Question.new
    if @current_user.nil?
      flash[:notice] = 'Please sign your in before posting a question.'
      redirect_to root_url
    end
  end

  def create
    current_user
    @question = Question.new(question_params)
    @question.user_id = @current_user.id

    if @question.save
      flash[:notice] = 'Question was created noticefully!'
      redirect_to(@question)
    else
      flash[:notice] = @question.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    current_user
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(best: :desc, created_at: :asc)

    if @current_user.nil?
      flash[:notice] = 'Please sign in before editing'
      render :show
    elsif @current_user.id != @question.user_id
      flash[:notice] = 'Please sign in before editing'
      redirect_to root_url
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = 'Question was updated noticefully!'
      redirect_to(@question)
    else
      flash[:notice] = @question.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    current_user
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.order(created_at: :asc)

    if @current_user.nil?
      flash[:notice] = 'Please sign in before deleting a question'
      render :show and return
    elsif @current_user.id != @question.user_id
      flash[:notice] = 'Please sign in before deleting this question'
      redirect_to root_url and return
    end

    @question.destroy
    flash[:notice] = 'Question was deleted noticefully!'
    redirect_to root_url
  end

  private

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      :user_id
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
  end

 private

 def user_params
   params.require(:user).permit(:provider, :uid, :name, :oauth_token, :oauth_expires_at)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="top-bar">
      <% if current_user %>
      Welcome
      <strong><%= current_user.name %></strong>!
      <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
      <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>

    <% if flash.any? %>
   <div class="alert callout">
       <strong><%= flash[:notice] %></strong>
   </div>
   <% end %>


  <div class="container">
    <div class="row">
      <div class="column">
    <%= yield %>
      </div>
    </div>
  </div>

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<a href="/questions">Back to questions</a>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<h1> Questions </h1>
<ul>
  <% @questions.each do |question| %>
  <li>
    <%= link_to "#{question.title}", question_path(question) %>
  </li>
  <% end %>
</ul>

<a href="/questions/new">Post a new question</a>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<h1>
  Title:
  <%= @question.title %>
</h1>
<p>
  Question:
  <%= markdown(@question.body) %>
</p>

<% if @answers.any? %>
  <h2> Current Answers: </h2>
<% end %>

<%= form_for [@question, @answer] do |f| %>

  <% @answers.each do |answer| %>
  <p>
    <% unless answer.best %>
    <%= link_to "Best", answer_path(answer), method: :put %>
    <% end %>

    <% if answer.best %>
    *** Best answer ***
    <% end %>
    <%= markdown(answer.body) %>
  </p>
  <% end %>

  <div class="field">
    <%= f.text_field :body %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

<br/>
<p>
  <%= link_to "Edit Question", edit_question_path(@question) %>
</p>
<p>
  <%= link_to "Delete Question", @question, method: :delete, data: { confirm: "Are you sure?" } %>
</p>
<a href="/">Go back to questions page</a>